package Store.Client.ServerCommunication;

public enum ClassType {
    EMPLOYEE, INVENTORY, PURCHASE_HISTORY, CUSTOMER, CHAT, EXCEPTION; 
    // EMPLOYEE, INVENTORY, PURCHASE_HISTORY, CUSTOMER_NEW, CUSTOMER_REGULAR, CUSTOMER_VIP; 
}
